//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOR.Front.Web.Pages.Pelerin {
    
    
    public partial class IDPhotoMaker {
        
        /// <summary>
        /// IDPhotoMakerUC1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VOR.Front.Web.UserControls.Pelerin.IDPhotoMakerUC IDPhotoMakerUC1;
    }
}
